# ReconHawk - PDF Report Generator
# Generates professional pentest-style PDF reports
# using ReportLab (free, open source)

from reportlab.lib.pagesizes  import A4
from reportlab.lib.styles     import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units       import cm
from reportlab.lib             import colors
from reportlab.platypus        import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, HRFlowable, PageBreak
)
from reportlab.lib.enums       import TA_CENTER, TA_LEFT
import datetime
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from database import db_manager
from reports  import remediation_data

# ─── Colour palette ───────────────────────────────
BG_DARK   = colors.HexColor("#0d1117")
BG_CARD   = colors.HexColor("#161b22")
ACCENT    = colors.HexColor("#58a6ff")
C_RED     = colors.HexColor("#ff6b6b")
C_ORANGE  = colors.HexColor("#ffa07a")
C_YELLOW  = colors.HexColor("#ffd700")
C_GREEN   = colors.HexColor("#90ee90")
C_GREY    = colors.HexColor("#8b949e")
C_WHITE   = colors.HexColor("#e6edf3")
C_BLACK   = colors.black

SEV_COLORS = {
    "CRITICAL": C_RED,
    "HIGH"    : C_ORANGE,
    "MEDIUM"  : C_YELLOW,
    "LOW"     : C_GREEN,
    "NONE"    : C_GREY,
    "INFO"    : ACCENT,
}

def sev_color(sev):
    return SEV_COLORS.get(str(sev).upper(), C_GREY)


def build_styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title", fontSize=26, textColor=C_WHITE,
            alignment=TA_CENTER, spaceAfter=6, fontName="Helvetica-Bold"
        ),
        "subtitle": ParagraphStyle(
            "subtitle", fontSize=13, textColor=C_GREY,
            alignment=TA_CENTER, spaceAfter=4
        ),
        "h1": ParagraphStyle(
            "h1", fontSize=16, textColor=ACCENT,
            spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold"
        ),
        "h2": ParagraphStyle(
            "h2", fontSize=13, textColor=C_WHITE,
            spaceBefore=10, spaceAfter=4, fontName="Helvetica-Bold"
        ),
        "body": ParagraphStyle(
            "body", fontSize=10, textColor=C_WHITE,
            spaceAfter=4, leading=14
        ),
        "small": ParagraphStyle(
            "small", fontSize=8, textColor=C_GREY,
            spaceAfter=2
        ),
        "code": ParagraphStyle(
            "code", fontSize=8, textColor=C_GREEN,
            fontName="Courier", spaceAfter=2
        ),
    }
    return styles


def severity_badge(sev):
    color_map = {
        "CRITICAL": "#ff6b6b",
        "HIGH"    : "#ffa07a",
        "MEDIUM"  : "#ffd700",
        "LOW"     : "#90ee90",
        "NONE"    : "#8b949e",
    }
    c = color_map.get(str(sev).upper(), "#8b949e")
    return f'<font color="{c}"><b>[{sev}]</b></font>'


def generate_report(scan_id, output_path=None):
    print(f"\n[*] Generating PDF report for scan #{scan_id}")

    data    = db_manager.get_scan_data(scan_id)
    scan    = data.get("scan")
    risk    = data.get("risk")
    ports   = data.get("ports",    [])
    cves    = data.get("cves",     [])
    findings= data.get("findings", [])
    subs    = data.get("subdomains",[])

    if not scan:
        print("[-] Scan not found in database")
        return None

    domain    = scan[1]
    scan_date = scan[2][:19]

    if not output_path:
        fname       = f"{domain}_scan{scan_id}_{datetime.datetime.now().strftime('%Y%m%d')}.pdf"
        output_path = os.path.join(config.REPORTS_DIR, fname)

    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    doc   = SimpleDocTemplate(
        output_path, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm,  bottomMargin=2*cm,
    )
    S     = build_styles()
    story = []

    # ── Cover Page ────────────────────────────────
    story.append(Spacer(1, 2*cm))
    story.append(Paragraph("🦅 ReconHawk", S["title"]))
    story.append(Paragraph("Automated Security Assessment Report", S["subtitle"]))
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", color=ACCENT))
    story.append(Spacer(1, 0.5*cm))

    cover_data = [
        ["Target Domain", domain],
        ["Scan Date",     scan_date],
        ["Scan ID",       f"#{scan_id}"],
        ["Report Date",   datetime.datetime.now().strftime("%Y-%m-%d %H:%M")],
        ["Generated By",  "ReconHawk v1.0"],
    ]
    cover_table = Table(cover_data, colWidths=[5*cm, 12*cm])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND",  (0,0),(-1,-1), BG_CARD),
        ("TEXTCOLOR",   (0,0),(0,-1),  C_GREY),
        ("TEXTCOLOR",   (1,0),(1,-1),  C_WHITE),
        ("FONTNAME",    (0,0),(0,-1),  "Helvetica-Bold"),
        ("FONTSIZE",    (0,0),(-1,-1), 10),
        ("ROWBACKGROUNDS",(0,0),(-1,-1),[BG_CARD, BG_DARK]),
        ("GRID",        (0,0),(-1,-1), 0.5, colors.HexColor("#30363d")),
        ("PADDING",     (0,0),(-1,-1), 8),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 1*cm))

    # Risk score box
    if risk:
        score    = risk[3]
        severity = risk[4]
        sc       = sev_color(severity)
        risk_data = [[
            f"Overall Risk Score",
            f"{score}/10",
            f"{severity}",
        ]]
        rt = Table(risk_data, colWidths=[7*cm, 4*cm, 6*cm])
        rt.setStyle(TableStyle([
            ("BACKGROUND", (0,0),(-1,-1), BG_CARD),
            ("TEXTCOLOR",  (0,0),(0,-1),  C_GREY),
            ("TEXTCOLOR",  (1,0),(1,0),   sc),
            ("TEXTCOLOR",  (2,0),(2,0),   sc),
            ("FONTNAME",   (0,0),(-1,-1), "Helvetica-Bold"),
            ("FONTSIZE",   (0,0),(-1,-1), 14),
            ("ALIGN",      (0,0),(-1,-1), "CENTER"),
            ("GRID",       (0,0),(-1,-1), 0.5, colors.HexColor("#30363d")),
            ("PADDING",    (0,0),(-1,-1), 12),
        ]))
        story.append(rt)

    story.append(PageBreak())

    # ── Executive Summary ─────────────────────────
    story.append(Paragraph("Executive Summary", S["h1"]))
    story.append(HRFlowable(width="100%", color=ACCENT, thickness=0.5))
    story.append(Spacer(1, 0.3*cm))

    if risk:
        summary_text = (
            f"A comprehensive security assessment was conducted against "
            f"<b>{domain}</b> on {scan_date}. The scan identified "
            f"<b>{risk[5]} CVEs</b> across {len(ports)} open ports on "
            f"{len(set(p[2] for p in ports))} hosts. "
            f"The overall risk score is <b>{risk[3]}/10</b> — rated "
            f"<b>{risk[4]}</b>. "
            f"Immediate attention is required for {risk[6]} Critical and "
            f"{risk[7]} High severity findings."
        )
        story.append(Paragraph(summary_text, S["body"]))
        story.append(Spacer(1, 0.4*cm))

        # Stats table
        stats = [
            ["Metric",           "Value"],
            ["Subdomains Found", str(len(subs))],
            ["Hosts Scanned",    str(len(set(p[2] for p in ports)))],
            ["Open Ports",       str(len(ports))],
            ["Total CVEs",       str(risk[5])],
            ["Critical CVEs",    str(risk[6])],
            ["High CVEs",        str(risk[7])],
            ["Medium CVEs",      str(risk[8])],
            ["Low CVEs",         str(risk[9])],
            ["Other Findings",   str(len(findings))],
        ]
        st = Table(stats, colWidths=[8*cm, 9*cm])
        st.setStyle(TableStyle([
            ("BACKGROUND",      (0,0),(-1,0),  ACCENT),
            ("TEXTCOLOR",       (0,0),(-1,0),  C_BLACK),
            ("FONTNAME",        (0,0),(-1,0),  "Helvetica-Bold"),
            ("ROWBACKGROUNDS",  (0,1),(-1,-1), [BG_CARD, BG_DARK]),
            ("TEXTCOLOR",       (0,1),(-1,-1), C_WHITE),
            ("GRID",            (0,0),(-1,-1), 0.5, colors.HexColor("#30363d")),
            ("FONTSIZE",        (0,0),(-1,-1), 10),
            ("PADDING",         (0,0),(-1,-1), 7),
        ]))
        story.append(st)

    story.append(PageBreak())

    # ── CVE Findings ──────────────────────────────
    story.append(Paragraph("CVE Findings", S["h1"]))
    story.append(HRFlowable(width="100%", color=ACCENT, thickness=0.5))
    story.append(Spacer(1, 0.3*cm))

    if cves:
        cve_table_data = [["Host", "Port", "CVE ID", "Score", "Severity", "Description"]]
        for c in sorted(cves, key=lambda x: x[5], reverse=True):
            cve_table_data.append([
                str(c[2])[:20],
                str(c[3]),
                str(c[4]),
                str(c[5]),
                str(c[6]),
                str(c[7])[:60],
            ])

        cve_table = Table(
            cve_table_data,
            colWidths=[3.5*cm, 1.5*cm, 2.8*cm, 1.5*cm, 2.2*cm, 5.5*cm]
        )
        style = [
            ("BACKGROUND", (0,0),(-1,0),  ACCENT),
            ("TEXTCOLOR",  (0,0),(-1,0),  C_BLACK),
            ("FONTNAME",   (0,0),(-1,0),  "Helvetica-Bold"),
            ("FONTSIZE",   (0,0),(-1,-1), 8),
            ("GRID",       (0,0),(-1,-1), 0.3, colors.HexColor("#30363d")),
            ("PADDING",    (0,0),(-1,-1), 5),
            ("ROWBACKGROUNDS",(0,1),(-1,-1),[BG_CARD, BG_DARK]),
            ("TEXTCOLOR",  (0,1),(-1,-1), C_WHITE),
        ]
        # Color severity column
        for i, c in enumerate(cves, start=1):
            sev = str(c[6]).upper()
            if sev in SEV_COLORS:
                style.append(("TEXTCOLOR", (4,i),(4,i), sev_color(sev)))
                style.append(("FONTNAME",  (4,i),(4,i), "Helvetica-Bold"))

        cve_table.setStyle(TableStyle(style))
        story.append(cve_table)
    else:
        story.append(Paragraph("No CVEs found.", S["body"]))

    story.append(PageBreak())

    # ── Other Findings ────────────────────────────
    story.append(Paragraph("Security Findings", S["h1"]))
    story.append(HRFlowable(width="100%", color=ACCENT, thickness=0.5))
    story.append(Spacer(1, 0.3*cm))

    if findings:
        f_data = [["Host", "Category", "Severity", "Title", "Detail"]]
        for f in sorted(findings, key=lambda x: x[4]):
            f_data.append([
                str(f[2])[:20],
                str(f[3]),
                str(f[4]),
                str(f[5])[:35],
                str(f[6])[:50],
            ])
        ft = Table(f_data, colWidths=[3*cm, 3*cm, 2.2*cm, 4.3*cm, 4.5*cm])
        fstyle = [
            ("BACKGROUND",    (0,0),(-1,0),  ACCENT),
            ("TEXTCOLOR",     (0,0),(-1,0),  C_BLACK),
            ("FONTNAME",      (0,0),(-1,0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0,0),(-1,-1), 8),
            ("GRID",          (0,0),(-1,-1), 0.3, colors.HexColor("#30363d")),
            ("PADDING",       (0,0),(-1,-1), 5),
            ("ROWBACKGROUNDS",(0,1),(-1,-1), [BG_CARD, BG_DARK]),
            ("TEXTCOLOR",     (0,1),(-1,-1), C_WHITE),
        ]
        for i, f in enumerate(findings, start=1):
            sev = str(f[4]).upper()
            if sev in SEV_COLORS:
                fstyle.append(("TEXTCOLOR",(2,i),(2,i), sev_color(sev)))
                fstyle.append(("FONTNAME", (2,i),(2,i), "Helvetica-Bold"))
        ft.setStyle(TableStyle(fstyle))
        story.append(ft)
    else:
        story.append(Paragraph("No additional findings.", S["body"]))

    story.append(PageBreak())

    # ── Remediation Checklist ─────────────────────
    story.append(Paragraph("Remediation Checklist", S["h1"]))
    story.append(HRFlowable(width="100%", color=ACCENT, thickness=0.5))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(
        "The following actions are recommended in priority order. "
        "Address Critical items immediately before proceeding to lower severities.",
        S["body"]
    ))
    story.append(Spacer(1, 0.4*cm))

    rem_data = [["#", "Action", "Priority", "Effort"]]
    idx = 1
    for item in remediation_data.GENERAL_CHECKLIST:
        rem_data.append([
            str(idx),
            item["item"],
            item["priority"],
            item["effort"],
        ])
        idx += 1

    rem_table = Table(rem_data, colWidths=[1*cm, 9*cm, 2.5*cm, 4.5*cm])
    rstyle = [
        ("BACKGROUND",    (0,0),(-1,0),  ACCENT),
        ("TEXTCOLOR",     (0,0),(-1,0),  C_BLACK),
        ("FONTNAME",      (0,0),(-1,0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 9),
        ("GRID",          (0,0),(-1,-1), 0.3, colors.HexColor("#30363d")),
        ("PADDING",       (0,0),(-1,-1), 6),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [BG_CARD, BG_DARK]),
        ("TEXTCOLOR",     (0,1),(-1,-1), C_WHITE),
    ]
    for i, item in enumerate(remediation_data.GENERAL_CHECKLIST, start=1):
        p = item["priority"]
        if p in SEV_COLORS:
            rstyle.append(("TEXTCOLOR", (2,i),(2,i), sev_color(p)))
            rstyle.append(("FONTNAME",  (2,i),(2,i), "Helvetica-Bold"))
    rem_table.setStyle(TableStyle(rstyle))
    story.append(rem_table)
    story.append(PageBreak())

    # ── Open Ports ────────────────────────────────
    story.append(Paragraph("Open Ports & Services", S["h1"]))
    story.append(HRFlowable(width="100%", color=ACCENT, thickness=0.5))
    story.append(Spacer(1, 0.3*cm))

    if ports:
        p_data = [["Host", "Port", "Protocol", "Service", "Product", "Version"]]
        for p in ports:
            p_data.append([
                str(p[2])[:22], str(p[3]), str(p[4]),
                str(p[5]), str(p[6])[:15], str(p[7])[:15],
            ])
        pt = Table(p_data, colWidths=[4*cm, 2*cm, 2*cm, 2.5*cm, 3*cm, 3.5*cm])
        pt.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,0),  ACCENT),
            ("TEXTCOLOR",     (0,0),(-1,0),  C_BLACK),
            ("FONTNAME",      (0,0),(-1,0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0,0),(-1,-1), 9),
            ("GRID",          (0,0),(-1,-1), 0.3, colors.HexColor("#30363d")),
            ("PADDING",       (0,0),(-1,-1), 5),
            ("ROWBACKGROUNDS",(0,1),(-1,-1), [BG_CARD, BG_DARK]),
            ("TEXTCOLOR",     (0,1),(-1,-1), C_WHITE),
        ]))
        story.append(pt)

    # ── Footer ────────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", color=C_GREY, thickness=0.3))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f"Generated by ReconHawk v1.0 — "
        f"github.com/YourUsername/ReconHawk — "
        f"{datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}",
        S["small"]
    ))

    doc.build(story)
    print(f"[✓] PDF report saved → {output_path}")
    return output_path


if __name__ == "__main__":
    # Test — generates PDF for most recent scan
    from database import db_manager as db
    db.init_db()
    scans = db.get_scans()
    if scans:
        path = generate_report(scans[0][0])
        print(f"Report: {path}")
    else:
        print("No scans found. Run main.py first.")
